### ISSUE TITLE
try to DRY your code

### ISSUE THREAD

**Issue by AndreiEgorov** [pjchong91/instanews#1]
Hi Pam, please refer to the "_base.scss" file. 

*you apply the same "width: auto" property to the same element twice:
line 158 and line 260.

* line 28 and 151  img.logo{
                                  height: auto;
                                  width: 100%;
                                             }

Perhaps, nesting items one into another(initially, when working on mobile version) would be helpful in  keeping track of the statements within the .scss file.

**Comment by pjchong91** [comment]
I have now incorporated this change. Thanks!
