### ISSUE TITLE
Loader gif placement

### ISSUE THREAD

**Issue by AndreiEgorov** [pjchong91/instanews#2]
Pam, 

When you make a selection in a mobile version of your app, a loader gif appears on top of the <p> and <select> elements.  Even though, it is a very small esthetic  issue, i wonder if it would look better if you could place the gif below the <select> by, perhaps taking giving a div (within which the gif is placed) a "margin-top: 4rem" or so.

**Comment by pjchong91** [comment]
Hey!! The loader gif has actually been translated to that position to match the RED Academy's mobile site.   I will be leaving it as is but I appreciate your suggestion!
