### ISSUE TITLE
HTML Semantics

### ISSUE THREAD

**Issue by AndreiEgorov** [pjchong91/instanews#3]
Pam,
 In "index.html" file within a "<div class="results">" (line 56)
 I would recommend using an unordered list with "li" and "div" elements appended each time an selection is made, as it is more semantically correct  ( <ul>  <li> <div>).

**Comment by rcass** [comment]
Hmm, this comment is a bit hard to understand.

I think the code you are trying to quote does not appear as you imagined.

@AndreiEgorov could you please just add a reference to the line of code by using the 'copy permalink' feature that github has.
This is when you navaigate to the file and line of code in github and when you click on the line of code, it gives you a few options such as 'copy permalink' 

Here is the documentation on how to do this in more detail https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/

**Comment by AndreiEgorov** [comment]
Hmm, sorry for being unclear.

Please, refer to the line below:
https://github.com/pjchong91/instanews/blob/801262831372a89b042e7d73f397afc4e72e569f/index.html#L56

Currently, this is a div element (with "results" class ) to which a set of 12 divs is appended when a user makes a selection.
What I was trying to emphasize is that, perhaps, it is better to insert a <ul> element within that div (or even replace the div with the <ul>) and then have <li> elements (with divs attached to them) append to the <ul> when the  user makes a selection.  This, in my opinion is more semantically correct as instead of a set of divs an unordered list with list items is used to display the articles on a webpage.

**Comment by AndreiEgorov** [comment]
* correction:

... it is better to insert a "ul" element within that div (or even replace the div with the) and then have "li" elements...

**Comment by rcass** [comment]
Thanks for fixing that message @AndreiEgorov . For future reference you can just edit original post or messages instead of having to write brand new ones 👍

**Comment by rcass** [comment]
- [x] To add on, to original issue, to make things more semantic, turn the container div into a section element instead @pjchong91 .

**Comment by pjchong91** [comment]
I definitely agree the divs could be made more semantic!  I changed my divs to section instead of li just because it was a simpler change to integrate.  However thank you both for the feedback!
