### ISSUE TITLE
Try not to over specify when possible

### ISSUE THREAD

**Issue by rcass** [pjchong91/instanews#6]
In _base.css there are some selectors that are more specific than they need to be.
`img.logo` could simply be `.logo`
and ` div.results` could simply be ` .results`
and `header.active` could be `.active`

**Comment by pjchong91** [comment]
Good point!  I have made these changes in my CSS. Thanks!

**Comment by rcass** [comment]
Perfect!

For future referance you can make it easier for the other person to verify your solution by linking to the commit or commits where the fix was made like this c9b4307b6158a2bf14b4d7b67829dd92366165d8

Here is the docs/instructions on how do to it as well :)
https://help.github.com/articles/autolinked-references-and-urls/
